export type Product = {
  id: string;
  name: string;
  description: string;
  price: string;
  originalPrice?: string;
  image: string;
  images?: string[];
  sizes?: string[];
  stock?: boolean;
  tags: {
    text: string;
    variant: 'success' | 'destructive' | 'default' | 'secondary' | 'outline';
  }[];
  discount?: number;
};

export const products: Product[] = [
  {
    id: '1',
    name: 'Corrente tijolinho',
    description: '3mm',
    price: '89,99',
    originalPrice: '110,00',
    image: 'prod-1',
    images: ['prod-1'],
    sizes: ['70 cm'],
    stock: true,
    tags: [
      { text: '3 restantes', variant: 'destructive' },
    ],
    discount: 19,
  },
  {
    id: '2',
    name: 'Corrente com Escudo Brasão',
    description: 'Banhada a Ouro 18k • Correntes • Estado: 10/10',
    price: '179,99',
    originalPrice: '257,13',
    image: 'prod-2',
    images: ['prod-2'],
    sizes: ['70 cm'],
    stock: true,
    tags: [
      { text: '2 restantes', variant: 'destructive' },
    ],
    discount: 30,
  },
  {
    id: '3',
    name: 'Corrente com Cruz Clássica',
    description: 'Banhada a Ouro 18k • Correntes • Estado: 10/10',
    price: '169,99',
    originalPrice: '212,49',
    image: 'prod-3',
    images: ['prod-3'],
    sizes: ['70 cm'],
    stock: true,
    tags: [],
    discount: 20,
  },
  {
    id: '4',
    name: 'Corrente tijolinho',
    description: '3mm',
    price: '109,99',
    originalPrice: '130,00',
    image: 'prod-4',
    images: ['prod-4'],
    sizes: ['70 cm'],
    stock: false,
    tags: [],
    discount: 15,
  },
  {
    id: '7',
    name: 'Corrente com Pingente Chave',
    description: 'Banhada a Ouro 18k • Correntes • Estado: 10/10',
    price: '149,99',
    originalPrice: '176,46',
    image: 'prod-7',
    images: ['prod-7'],
    sizes: ['70 cm'],
    stock: true,
    tags: [],
    discount: 15,
  },
    {
    id: '9',
    name: 'Corrente com Pingente Cruz Luxo',
    description: 'Banhada a Ouro 18k • Correntes • Estado: 10/10',
    price: '199,99',
    originalPrice: '222,21',
    image: 'prod-9',
    images: ['prod-9'],
    sizes: ['70 cm'],
    stock: true,
    tags: [
    ],
    discount: 10,
  },
  {
    id: '10',
    name: 'Corrente com Pingente Premium',
    description: 'Banhada a Ouro 18k • Correntes • Estado: 10/10',
    price: '219,99',
    originalPrice: '249,99',
    image: 'prod-10',
    images: ['prod-10'],
    sizes: ['70 cm'],
    stock: true,
    tags: [
      { text: '2 restantes', variant: 'destructive' },
    ],
    discount: 12,
  },
  {
    id: '13',
    name: 'Corrente cadeado',
    description: '2mm',
    price: '109,99',
    originalPrice: '220,00',
    image: 'prod-13',
    images: ['prod-13'],
    sizes: ['70 cm'],
    stock: true,
    tags: [],
    discount: 50,
  },
  {
    id: '14',
    name: 'Corrente tijolinho',
    description: '3mm',
    price: '119,99',
    originalPrice: '240,00',
    image: 'prod-14',
    images: ['prod-14'],
    sizes: ['70 cm'],
    stock: true,
    tags: [],
    discount: 50,
  },
  {
    id: '15',
    name: 'Corrente piastrine',
    description: '2mm',
    price: '109,99',
    originalPrice: '250,00',
    image: 'prod-15',
    images: ['prod-15'],
    sizes: ['70 cm'],
    stock: true,
    tags: [{ text: 'Novo', variant: 'success' }],
    discount: 56,
  },
  {
    id: '16',
    name: 'Corrente tijolinho',
    description: '3mm',
    price: '89,99',
    originalPrice: '210,00',
    image: 'prod-16',
    images: ['prod-16'],
    sizes: ['70 cm'],
    stock: true,
    tags: [],
    discount: 57,
  },
  {
    id: '17',
    name: 'Corrente Leão',
    description: 'Banhada a Ouro 18k • Correntes • Estado: 10/10',
    price: '229,99',
    originalPrice: '270,00',
    image: 'prod-17',
    images: ['prod-17'],
    sizes: ['70 cm'],
    stock: true,
    tags: [{ text: 'Mais Vendido', variant: 'default' }],
    discount: 15,
  },
  {
    id: '18',
    name: 'Corrente Âncora',
    description: 'Banhada a Ouro 18k • Correntes • Estado: 10/10',
    price: '159,99',
    originalPrice: '190,00',
    image: 'prod-18',
    images: ['prod-18'],
    sizes: ['70 cm'],
    stock: true,
    tags: [],
    discount: 16,
  },
];
